### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Paul-Vasylenko** [Paul-Vasylenko/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Paul-Vasylenko-add** [comment]
**let this be like a small interview**

--Michael, were you really guilty in child molestation charges?
--Oh, dear. It's really hard for me to talk about it and all these people who say so know that too. I had a very difficult childhood, and I would never do harm to my children. I don't want them to think about me the way I thought about father of mine.

--How many plastic operations did you have? 
--I don't understand the way people think about the appearance of others. Why did they make me guilty for my skin being changed because of an illness? Aren't they go to the beaches to have themselves sunbathed and change their skin?
I had some operations on my nose, hair, eyebrows. But there are no tens of them, that people say. Don't believe the press.

--Did you forgive your father?
--it was very difficult for me to do it, but I did forget him. He killed my childhood, he stole my brothers` childhood, but I forgive him. Just look on the result of his action. Look at me. I am happy of what I am. I really want to just.. like.. hug him and call him "daddy", but he angers and says "I am Joseph for you.". I am so envious of those children who had such a nice childhood. I would never do so with my children.

--Are you still dancing?
--Oh, nah. Yes, sometimes I dance, just because i feel music and it is a part of my life. But now I don't have much strength to dance as I was  20 or 30 y.o.

--Do you like your own music?
--If I didn't - I wouldn't get a success at all, I'm sure.

--And now the question we are here for: How are you still alive and why did you invented your death?
--I was so tired of all this fame. I was very weak because of medical addiction and all of these courts and everything.. I could continue living at home on the money my relatives earned, but I wanted to make history one more time. 
that's why I announced a new tour "this is it". I was really preparing for it, and I was even going to perform some concerts, but once I got really bad. My doctor said that I wouldn't be able to perform at all for the next  3 months at least. That's why we started out plan of fake death earlier. 
I really appreciate fans who were thinking about me being alive living somewhere else  with a changed appearance...  And really, these people are the only one reason why I'm here talking to you, giving an interview about me being alive, lol)

--Are you going to perform?
--Not a big scene for sure. Maybe I will give one online perfomance from my house without any effects, just a tiny show of my best songs for my closest fans, and that all.

--Have you overcome your addiction and pain?
--Yes. Now I am a completely healthy person, but I'm still 60 y.o.

--Do you love yourself now? 
--Oh.. In past I always used to say "I'm never satisfied of myself", I can do better. I looked at myself in the mirror and I didn't like the way I looked. Now, when I am feeling freedom -- I've started to love myself. I really enjoy the life and the way I lived the live.

--Thank you Michael!
--Yeah, thank you too, bye :)
